### PR TITLE
Prevent the UASocketClient from hanging

### PR DESCRIPTION
**Pull request by AlexejStukov**
Added a timeout to the socket connection that prevents the ``UASocketClient`` from hanging on  ``_receive`` in ``_run``.

### CODE REVIEW

**Comment by oroulet** [comment]
Maybe should we use another timeout variable. Add a socket_timeout to class.
What should be default value of such timeout? Not sure...

**Comment by AlexejStukov** [comment]
Is there a size limitation on the received packages?

**Comment by oroulet** [comment]
A message has a max size if I remember well. You need to look at member
variables in headers or connection settings....

**Comment by AlexejStukov** [comment]
The only thing i can find is ``self.MaxMessageSize = 0  # No limits`` and the likes... .

**Comment by oroulet** [comment]
Yes I tried to set everything to no limits. What is your issue?

**Comment by AlexejStukov** [comment]
I was searching for a size limitation in the sources to estimate a reasonable timeout. 
Shouldn't the package size be restricted by tcp? Then we could assume 64kb. So 10 seconds might be ok?

**Comment by oroulet** [comment]
I think timeout is only user of establishing and stopping connection, so
packet size does not influence this. Something between 2 and 10 is probably
ok

**Comment by AlexejStukov** [comment]
Ok, then I'll leave it at 10 seconds. If somebody needs a longer or shorter time he can change it easily.

**Pull request merged**
