### PR TITLE
Added decorator for class members

### PR DESCRIPTION
**Pull request by destogl**
Added new decorator to automatically convert from and to variants for method which are class members since other is not working with them.

### CODE REVIEW

**Comment by oroulet** [comment]
Can't we merge both to have only one decorator?

**Comment by destogl** [comment]
Yes maybe, but it can be tricky, since if there is member class you always get "self" as the first argument... and in other case you get parent...

**Comment by oroulet** [comment]
then we should rename them
uamethod should in fact be uafunction and the other uamethod.
Can you do it?

**Comment by oroulet** [comment]
not sure now. method is the name used by opcua

**Comment by oroulet** [comment]
I vote for rename anyway

**Comment by destogl** [comment]
Just wait a sec, I try to hack it into one and than we decide...

**Comment by destogl** [comment]
Solved, I donesn't look bad :)

so the name can stay...

**Pull request merged**
