### PR TITLE
Add ua to python mirroring example

### PR DESCRIPTION
**Pull request by zerox1212**
Please review this example and let me know if it is clear and worth adding to our collection. I found it very useful in my personal projects and would like to expand it.

Do not merge because I didn't test it yet.

Ultimate goal would be to generate python objects that subclass `UaObject` from UA Modeler for fast application development.

### CODE REVIEW

**Comment by oroulet** [comment]
I could not see anything bad with that approach. You could override __setattr__ so anytime a member is written it is written to server. Or use @property

**Comment by zerox1212** [comment]
I thought about overriding `setattr`, but I was worried about performance. For example if the user wants to do some operations on a variable without lots of client updates. This way can publish it explicitly.

**Comment by oroulet** [comment]
True. A complete class could have a batch parameter, that sync attributes on the fly or when calling a sync method.

**Comment by oroulet** [comment]
btw calling the method write is probably more correct than publish since the call is called uawrite

**Comment by zerox1212** [comment]
I will change this to `write` and test it so we can merge.

**Comment by zerox1212** [comment]
This example works and is ready to merge. It could probably use some optimizations, but at least it's a start. Adding more helper objects to this SDK should make it easier to use.

**Pull request merged**
