### PR TITLE
Fix error with guid as NodeIdType

### PR DESCRIPTION
**Pull request by Michael-List**
Fix error with guid as NodeIdType. For more information see issue #972

### CODE REVIEW

**Comment by oroulet** [comment]
That seems to make sense. Is there any case where someone will want to provide bytes and not uuid object?

**Comment by Michael-List** [comment]
If someone would like to provide bytes we have to convert it to an uuid afterwards. If it's an byte we run into an error because we cannot pack it like below.

ua_binary.py:
```
class _Guid(object):
    @staticmethod
    def pack(guid):
        # convert python UUID 6 field format to OPC UA 4 field format
        f1 = Primitives.UInt32.pack(guid.time_low)
        f2 = Primitives.UInt16.pack(guid.time_mid)
        f3 = Primitives.UInt16.pack(guid.time_hi_version)
        f4a = Primitives.Byte.pack(guid.clock_seq_hi_variant)
        f4b = Primitives.Byte.pack(guid.clock_seq_low)
        f4c = struct.pack('>Q', guid.node)[2:8]  # no primitive .pack available for 6 byte int
        f4 = f4a + f4b + f4c
        # concat byte fields
        b = f1 + f2 + f3 + f4

        return b
```

**Comment by zerox1212** [comment]
I think I wrote the binary protocol for GUID. We should not use a bytes object. If someone supplies bytes we need to convert it to UUID as mentioned above. However I would recommend people use the python UUID whenever possible, so I do not think it's worth supporting bytes at this time.

**Comment by oroulet** [comment]
Ok

**Pull request merged**
