### PR TITLE
fixes for opcua-modeler

### PR DESCRIPTION
**Pull request by oroulet**

### CODE REVIEW

**Comment by zerox1212** [comment]
You did some clean up that I was planning to do this weekend. Thanks for the improvements.

**Comment by oroulet** [comment]
Ok. Are you working on it the next days? I am traveling so I may have some time

**Comment by oroulet** [comment]
But I am focusing on ui and bugs in opcua lib, so feel Fri to work on it :-)

**Comment by zerox1212** [comment]
Later this week I might look at adding methods.

Also I forgot to add the description element to etree. That can now be added to the 'common' node stuff. I think every UA Node can have a description.

**Pull request merged**
