### PR TITLE
more chunk debug, do not check chunk num for secure_open

### PR DESCRIPTION
**Pull request by oroulet**

### CODE REVIEW

**Comment by okyame** [comment]
Hi,

I do some tests. I get this error on client side:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/okyame/_DEV/project/python-opcua/opcua/client/client.py", line 71, in run
    val = server_state.get_value()
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 153, in get_value
    result = self.get_data_value()
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 162, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 273, in get_attribute
    result = self.server.read(params)
  File "/home/okyame/_DEV/project/python-opcua/opcua/client/ua_client.py", line 337, in read
    data = self._uasocket.send_request(request)
  File "/home/okyame/_DEV/project/python-opcua/opcua/client/ua_client.py", line 83, in send_request
    data = future.result(self.timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

Traceback (most recent call last):
  File "project-example_test.py", line 120, in <module>
    read_modify_node_value(l2f_serv, nodeid)
  File "project-example_test.py", line 54, in read_modify_node_value
    my_value = l2f_serv.get_node_value(nodeid)
  File "/home/okyame/_DEV/project/project-opcua-server/l2f_opcua_package_build/test/l2f_opcua_test.py", line 269, in get_node_value
    return node.get_value()
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 153, in get_value
    result = self.get_data_value()
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 162, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/node.py", line 273, in get_attribute
    result = self.server.read(params)
  File "/home/okyame/_DEV/project/python-opcua/opcua/client/ua_client.py", line 337, in read
    data = self._uasocket.send_request(request)
  File "/home/okyame/_DEV/project/python-opcua/opcua/client/ua_client.py", line 83, in send_request
    data = future.result(self.timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
```

And this on server side:

```
INFO:opcua.server.internal_subscription:publish request with acks []
ERROR:opcua.server.binary_server_asyncio:Exception raised while parsing message from client, closing
Traceback (most recent call last):
  File "/home/okyame/_DEV/project/python-opcua/opcua/server/binary_server_asyncio.py", line 75, in _process_data
    ret = self.processor.process(hdr, buf)
  File "/home/okyame/_DEV/project/python-opcua/opcua/server/uaprocessor.py", line 83, in process
    msg = self._connection.receive_from_header_and_body(header, body)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 310, in receive_from_header_and_body
    return self._receive(chunk)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 341, in _receive
    self._check_incoming_chunk(msg)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 290, in _check_incoming_chunk
    raise ua.UaError("Received chunk: {0} with wrong sequence expecting: {1}, received: {2}, spec says to close connection".format(chunk, self._peer_sequence_number, num))
opcua.ua.uaerrors._base.UaError: Received chunk: MessageChunk(Header(type:b'MSG', chunk_type:b'F', body_size:132, channel:7), SequenceHeader(SequenceNumber:7632, RequestId:7632 ), SymmetricAlgorithmHeader(TokenId:14 ), 72 bytes) with wrong sequence expecting: 7630, received: 7632, spec says to close connection
ERROR:opcua.server.binary_server_asyncio:Exception raised while parsing message from client, closing
Traceback (most recent call last):
  File "/home/okyame/_DEV/project/python-opcua/opcua/server/binary_server_asyncio.py", line 75, in _process_data
    ret = self.processor.process(hdr, buf)
  File "/home/okyame/_DEV/project/python-opcua/opcua/server/uaprocessor.py", line 83, in process
    msg = self._connection.receive_from_header_and_body(header, body)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 310, in receive_from_header_and_body
    return self._receive(chunk)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 341, in _receive
    self._check_incoming_chunk(msg)
  File "/home/okyame/_DEV/project/python-opcua/opcua/common/connection.py", line 290, in _check_incoming_chunk
    raise ua.UaError("Received chunk: {0} with wrong sequence expecting: {1}, received: {2}, spec says to close connection".format(chunk, self._peer_sequence_number, num))
opcua.ua.uaerrors._base.UaError: Received chunk: MessageChunk(Header(type:b'MSG', chunk_type:b'F', body_size:100, channel:7), SequenceHeader(SequenceNumber:7633, RequestId:7633 ), SymmetricAlgorithmHeader(TokenId:14 ), 39 bytes) with wrong sequence expecting: 7630, received: 7633, spec says to close connection
INFO:opcua.common.subscription:Publish callback called with result: PublishResult(SubscriptionId:78, AvailableSequenceNumbers:[], MoreNotifications:False, NotificationMessage:NotificationMessage(SequenceNumber:2410, PublishTime:2020-02-19 13:48:33.924129, NotificationData:[]), Results:[], DiagnosticInfos:[])
INFO:opcua.server.subscription_service:publish request with acks [SubscriptionAcknowledgement(SubscriptionId:78, SequenceNumber:2410)]
INFO:opcua.server.internal_subscription:publish request with acks [2410]
```

**Comment by oroulet** [comment]
Thanks @okyame so my patch did not solve the issue. I have no idea why the server make that jump for a normal message. Also I tried many things today but I could not reproduce that issue,
Can your reproduce this easily? Can you make a Wireshark recording?might be our only solution to understand what is happening.

**Comment by fcaspani01** [comment]
I try this PR but i have this error from OPC UA Server (SINUMERIK OPC UA Server)
After about 10 minutes client raise "timeout on open_secure_channel()"

Schermata 2020-03-05 alle 14 14 27

**Comment by oroulet** [comment]
Do you use encryption? Can you reproduce and log with wirershark?

**Comment by oroulet** [comment]
Does that happen without encryption? 
Also this seems to be a different error. Not the chunk error

**Comment by fcaspani01** [comment]
Yes, I use security_policy="Basic128Rsa15" and security_mode="SignAndEncrypt".
More later i will send you a wireshark session

**Pull request merged**
