### PR TITLE
Example custom enumerations

### PR DESCRIPTION
**Pull request by bitkeeper**
If you want to try it out; doesn't work on the current master it requires fixes for

add_subtype - requires extra argument for NodeClass. see PR #231
add_variable - requires extra argument for datatype. see PR #235

### CODE REVIEW

**Comment by bitkeeper** [comment]
Looks like the Travis error has nothing to do with this specific PR ?

**Comment by destogl** [comment]
This seams to be Travis error, but we take care about that when are stuff are clear

**Comment by destogl** [comment]
@bitkeeper: Could you check #241 if this is OK for you for adding custom types. It would be good to update your example according to that and than we can start work on instantiate as @oroulet proposed.

**Comment by bitkeeper** [comment]
The requirements for this PR are already merged (PR #231 #235). Is it possible to first merge this PR and that I then make a new PR for an undated example and also include an updated tests/server-customobject.py.

**Comment by destogl** [comment]
OK

**Comment by bitkeeper** [comment]
Thanks !

**Pull request merged**
