### PR TITLE
Standard address space  spec version 1.04 

### PR DESCRIPTION
**Pull request by cirp-usf**
For previous discussion, see #572 and #574

### CODE REVIEW

**Comment by cirp-usf** [comment]
When opcua is imported, the failure to include some nodes at the first try generate some annoying warnings:
```
add_node: while adding node NumericNodeId(i=15957), requested parent node NumericNodeId(i=11715) does not exists
add_node: while adding node NumericNodeId(i=15958), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15959), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15960), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15961), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15962), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15963), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15964), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16134), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16135), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16136), requested parent node NumericNodeId(i=15957) does not exists
```
The code passes the tests however.

**Comment by cirp-usf** [comment]
When opcua is imported, the failure to include some nodes at the first try generate some annoying warnings:
```
add_node: while adding node NumericNodeId(i=15957), requested parent node NumericNodeId(i=11715) does not exists
add_node: while adding node NumericNodeId(i=15958), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15959), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15960), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15961), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15962), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15963), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=15964), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16134), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16135), requested parent node NumericNodeId(i=15957) does not exists
add_node: while adding node NumericNodeId(i=16136), requested parent node NumericNodeId(i=15957) does not exists
```
The code passes the tests however.

**Comment by oroulet** [comment]
Clean and correct patch! Well done

**Comment by oroulet** [comment]
Concerning warning. What is happening when a node is not inserted? The insertion is postponed? What happens if it fails the second time?

**Comment by oroulet** [comment]
The easiest solution is to change warning to info. so it does not get printed by default. 
It is also possible to check if parent exist before trying to add the node, but I am afraid to add one more nodeid dict query here. It is already very slow... but maybe this does not change much...

**Comment by cirp-usf** [comment]
I really don't like the warnings getting printed for the standard address space. But I'm afraid changing the warning to info would make it very difficult to find bugs when there actually is a problem with other xml node sets or nodes the user is trying to include. The warning is emitted [here](https://github.com/FreeOpcUa/python-opcua/blob/72629f5e80573563a2d8a08467bbb7a6244b85c4/opcua/server/address_space.py#L213). 

I'm calling the method `_add_node` directly from `try_add_nodes` instead of calling `add_nodes`. One possibility would be to add an extra parameter to `_add_node` that would make it emit an info instead of an warning. The parameter's default value would cause warnings to be emitted. Then I would make `try_add_nodes` use that parameter so when the standard address space is loaded there are no warnings. But when the user adds nodes via the usual interface, a warning would be emitted if the insertion fails.

Would such a solution be acceptable? This PR is so nice and organized. But I think I may need to add yet another commit...

**Comment by oroulet** [comment]
Info is no problem. Anyway an explicit ua error status is returned

**Comment by oroulet** [comment]
You can add another commit to fix warning

**Comment by oroulet** [comment]
Thanks for good work

**Pull request merged**
