### PR TITLE
Update uatypes.py

### PR DESCRIPTION
**Pull request by AndreasHeine**
see asyncua: https://github.com/FreeOpcUa/opcua-asyncio/pull/231

### CODE REVIEW

**Comment by AndreasHeine** [comment]
```
======================================================================

FAIL: test_subscription_count (tests_server.TestServer)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/FreeOpcUa/python-opcua/tests/tests_subscriptions.py", line 121, in test_subscription_count

    self.assertEqual(myhandler.datachange_count, nb + 1)

AssertionError: 12 != 13

----------------------------------------------------------------------

Ran 408 tests in 49.048s

FAILED (failures=1, skipped=8)

The command "./run-tests.sh" exited with 1.

Done. Your build exited with 1.
```

**Comment by AndreasHeine** [comment]
@oroulet travis dont like me...

**Comment by oroulet** [comment]
That test falls easily. Should be fixed

**Comment by AndreasHeine** [comment]
@oroulet thats... on the 3rd try ;) can be merged!

**Pull request merged**
