### PR TITLE
Add default value option to xml importer

### PR DESCRIPTION
**Pull request by zerox1212**
Allows user to decide how to handle xml import
enable_default_values=False means any xml Values that are not set (type None) will be set to data type Null by server
enable_default_values=True means any xml Values that are None will be initialized with a default value to preserve the xml data type

See https://github.com/FreeOpcUa/python-opcua/issues/286

### CODE REVIEW

**Comment by zerox1212** [comment]
Is there some concern about merging this?

**Comment by zerox1212** [comment]
My project I'm working with currently uses everything from the recent merges. If you can merge this I can sync my project and test with real software.

**Comment by zerox1212** [comment]
I don't think rebase worked, I have never tried to use that before...

**Comment by zerox1212** [comment]
It wasn't a bug in the other software.
The problem is that if a xml Node does not have a Value tag, importer sets the datatype of the variable, then it sets the value to python type None. Then when the node gets created in the server the server sees a value of None and overwrites the original node data type to Null. After that, the only way undo the node being Null datatype is to write to it from the server. No clients can write to a datatype null.

This change will try to preserve the datatype set in the XML.

**Comment by zerox1212** [comment]
I can't figure out how to correct these conflicts... I'm just going to make a new PR from the latest master.

**Comment by oroulet** [comment]
Try to make sample code to demonstrate issue first, so we can discuss the
best way to resolve it

**Comment by oroulet** [comment]
I am currently very busy at work. I should take a deeper look at this
default value stuff

**Comment by oroulet** [comment]
Can you write sample code to show that issue? Write it so we can use your
code as a test later

**Pull request closed without merging**
