### PR TITLE
BadIdentityTokenInvalid EncryptionAlgorithm not None

### PR DESCRIPTION
**Pull request by mparini**
I find the problem with Arburg machine, I have to change :
params.UserIdentityToken.EncryptionAlgorithm = ''
in
params.UserIdentityToken.EncryptionAlgorithm = None

in opcua/client/client.py
change:
def _add_user_auth(self, params, username, password):
params.UserIdentityToken = ua.UserNameIdentityToken()
params.UserIdentityToken.UserName = username
policy_uri = self.server_policy_uri(ua.UserTokenType.UserName)
if not policy_uri or policy_uri == security_policies.POLICY_NONE_URI:
if self.server_url.password:
self.logger.warning("Sending plain-text password")
params.UserIdentityToken.Password = password
**params.UserIdentityToken.EncryptionAlgorithm = None**
elif self.server_url.password:
data, uri = self._encrypt_password(password, policy_uri)
params.UserIdentityToken.Password = data
params.UserIdentityToken.EncryptionAlgorithm = uri
params.UserIdentityToken.PolicyId = self.server_policy_id(ua.UserTokenType.UserName, b"username_basic256")

Thanks
Massimo Parini

### CODE REVIEW

**Comment by oroulet** [comment]
There is something wrong here. there are many ways to fix this but the simplest is to do a new fork using github button. clone it locally, make your changes, commit, then create a PR using github interface

**Comment by oroulet** [comment]
@mparini in its current state I cannot review or this this PR. Can you fix it?

**Comment by zerox1212** [comment]
@oroulet can you close this pull request for now? I don't think he is going to fix it and it keep showing up in notifications.

**Comment by oroulet** [comment]
fixed it myself:_ https://github.com/FreeOpcUa/python-opcua/commit/ff361cb6c897ba3b9c39cbbfb1ed0953ebdcfe65
should not breakl anythong... hopefully...

**Pull request closed without merging**
