### PR TITLE
Issue #226

### PR DESCRIPTION
**Pull request by TheAtlantis**
Add server Event for client Item subscription

Usage : 
`self.server.subscribe_server_event("create_monitored_items", self.create_monitored_items)
self.server.subscribe_server_event("modify_monitored_items", self.modify_monitored_items)
self.server.subscribe_server_event("delete_monitored_items", self.delete_monitored_items)`

### CODE REVIEW

**Comment by destogl** [comment]
Can this be somehow merged with current event implementation? At least for the event side. And I think we have already EventDispatcher for the changeValue events, can this be reused?

**Comment by TheAtlantis** [comment]
Maybe but I don't see how to do that. 
The SubscriptionService create a subscribe on internal item ( with StatusCode, PublishingInterval etc.).
I think to reusing EventDispatcher to implement ServerDiagnostics #227  for example. 

If you have a better solution, I'll take it.

**Comment by TheAtlantis** [comment]
Actually, the server class provide subscribe_server_event or unsubscribe_server_event method. 
If you want I can rename this method (and more : EventDispatcher, etc..) with "callback" like this : 
- subscribe_server_callback 
- CallbackDispatcher

**Comment by destogl** [comment]
OK. I was misguided with the name event. Renaming it to callbacks seams good. If you could add some tests for it into `test/test_server.py` would be great :)

**Comment by oroulet** [comment]
@TheAtlantis OK,  rename them as you think is best but avoid using Event terminology. Maybe Signal is another possibility...
Then I do not like using arbitraty strings as event/callback keys, this is very error prone. What about using an enum? other proppositions?

**Comment by destogl** [comment]
Enums are good. Similar to keys in `VariantType` class

**Comment by TheAtlantis** [comment]
I have commit server exemple for callback use and use callback as event name. 
Callback keys are enum now.

**Comment by destogl** [comment]
I would move `callback.py` from `common` into `server`

**Comment by oroulet** [comment]
looks OK. Although as @destogl wrote, maybe this is server only?

**Pull request merged**
