### PR TITLE
Cleanup crypto

### PR DESCRIPTION
**Pull request by alkor**
Remove unneeded function uacrypto.x509_to_der() (equivalent to uacrypto.der_from_x509()).

Pretty-print server certificate in uadiscover.

### CODE REVIEW

**Comment by oroulet** [comment]
same error as last time. seems to be a random error in token id. 

est_variable_data_type (__main__.AdminTestClient) ... ok

ERROR:opcua.server.binary_server_asyncio:Exception raised while parsing message from client, closing

Traceback (most recent call last):

  File "./opcua/server/binary_server_asyncio.py", line 83, in _process_data

    ret = self.processor.process(hdr, buf)

  File "./opcua/server/uaprocessor.py", line 66, in process

    msg = self._connection.receive_from_header_and_body(header, body)

  File "./opcua/ua/uaprotocol_hand.py", line 614, in receive_from_header_and_body

    return self._receive(chunk)

  File "./opcua/ua/uaprotocol_hand.py", line 645, in _receive

    self._check_incoming_chunk(msg)

  File "./opcua/ua/uaprotocol_hand.py", line 576, in _check_incoming_chunk

    self._security_token.TokenId))

Exception: Wrong token id 14, expected 15

('Cleanup client connection: ', ('::1', 45901, 0L, 0L))

Exception in thread Thread-5:

Traceback (most recent call last):

  File "/opt/python/pypy-2.5.0/lib-python/2.7/threading.py", line 806, in __bootstrap_inner

    self.run()

  File "/opt/python/pypy-2.5.0/lib-python/2.7/threading.py", line 759, in run

    self.__target(*self.__args, **self.__kwargs)

  File "./opcua/client/binary_client.py", line 92, in _run

    self._receive()

  File "./opcua/client/binary_client.py", line 99, in _receive

    msg = self._connection.receive_from_socket(self._socket)

  File "./opcua/ua/uaprotocol_hand.py", line 637, in receive_from_socket

    header = Header.from_string(socket)

  File "./opcua/ua/uaprotocol_hand.py", line 121, in from_string

    hdr.MessageType, hdr.ChunkType, hdr.packet_size = struct.unpack("<3scI", data.read(8))

  File "./opcua/common/utils.py", line 95, in read

    chunk = self.socket.recv(size)

  File "/opt/python/pypy-2.5.0/lib-python/2.7/socket.py", line 206, in recv

    return self._sock.recv(buffersize, flags)

error: [Errno 104] Connection reset by peer

ERROR

**Comment by alkor** [comment]
Yes, "Wrong token id". I'm trying to find why it is possible.

**Comment by alkor** [comment]
I've found what's wrong. There was a race condition in client's KeepAlive thread. In disconnect() Client could send CloseSessionRequest and OpenSecureChannel(Renew) almost simultaneously.

**Comment by oroulet** [comment]
I am not sure I understand but I trust you. will see what happens

**Pull request merged**
