### PR TITLE
fix: dictionary changed size during iteration

### PR DESCRIPTION
**Pull request by brubbel**
https://github.com/FreeOpcUa/python-opcua/issues/659
https://github.com/FreeOpcUa/python-opcua/issues/661

### CODE REVIEW

**Comment by oroulet** [comment]
Ok. This lock thing is dangerous. I will have a look

**Comment by brubbel** [comment]
True, looking with a fresh mind, it is not quite right.

**Comment by brubbel** [comment]
[Here](https://github.com/FreeOpcUa/python-opcua/blob/79e09e8082e383739fd7e36c9c1cf5467d470acd/opcua/server/internal_subscription.py#L205), [here](https://github.com/FreeOpcUa/python-opcua/blob/79e09e8082e383739fd7e36c9c1cf5467d470acd/opcua/server/internal_subscription.py#L243) and [here](https://github.com/FreeOpcUa/python-opcua/blob/79e09e8082e383739fd7e36c9c1cf5467d470acd/opcua/server/internal_subscription.py#L246) are calls from MonitoredItemService directly into InternalSubscription, thereby bypassing the RLock() of the InternalSubscription object. There is a lock in place, but it is the RLock() of the MonitoredItemService object.
So, a `with self._lock()` in [_enqueue_event](https://github.com/FreeOpcUa/python-opcua/blob/79e09e8082e383739fd7e36c9c1cf5467d470acd/opcua/server/internal_subscription.py#L385) should be sufficient.

**Comment by oroulet** [comment]
But each lock is probably only to protect one sensitive structure. Do you have overview over which one?

**Comment by brubbel** [comment]
I'm not using opcua events for the moment, so I guess the [enqueue_datachange_event](https://github.com/FreeOpcUa/python-opcua/blob/79e09e8082e383739fd7e36c9c1cf5467d470acd/opcua/server/internal_subscription.py#L205) is the cause.

**Pull request merged**
