### PR TITLE
Fix to avoid circular import, including remove of *args

### PR DESCRIPTION
**Pull request by bitkeeper**
More clean construction then the current one.

### CODE REVIEW

**Comment by georgschoelly** [comment]
Is there a reason not to do simple assignments? Instead of

    class Node(object):
        ....
        def add_folder(self, nodeid, bname):
            return  opcua.common.manage_nodes.create_folder(self, nodeid, bname)

we could do:

    class Node(object):
        ...
        add_folder = opcua.common.manage_nodes.create_folder

and thinking a bit more about it, why don't we do that programatically? It's possible to create a [class decorator](http://www.ianbicking.org/blog/2007/08/opening-python-classes.html) which could be used like this: 

```
@extend(opcua.common.node.Node)
class Node(object):
    def some_method(self, args):
        pass
```

**Comment by oroulet** [comment]
yes originally it was an assignment until we got a circular import issue with python2. Does it work? If it works, it is the cleanest thing

**Comment by maljac** [comment]
I like the proposal from @georgschoelly. The only thing that is not so nice is probably the missing IDE support when using the `@extend` mechanism.

**Comment by georgschoelly** [comment]
Another possibility:

~~~
class _NodeBasics(object):
    def method1(self):
        pass

class _NodeCreation(object):
    def method2(self):
         pass

class Node(_NodeBasics, _NodeCreation):
    pass
~~~

With some code such that `_NodeBasics` and `_NodeCreation` cannot be instantiated and that checks for methods / instance variables defined in both.

**Comment by georgschoelly** [comment]
We could also do some subclassing magic:

**Comment by oroulet** [comment]
@georgschoelly last proposition seems a bit overkill. the only issue here is that I did not want to have a file which is too big. I would prefer assignment, this is the solution with least code and that should not break anything. Does assignment work now?

**Comment by oroulet** [comment]
otherwise I will just merge your PR

**Comment by georgschoelly** [comment]
I'll have a look if it works with simple assignments, I should be able to do that within the next hour.

**Comment by georgschoelly** [comment]
I wasn't able to get simple assignments to work and I currently don't have the time for it. I've improved on it slightly by using `*args*` and `**kwargs`, this ensures that if we change the methods in `manage_nodes.py`, we don't need to change it in `node.py` as well.

https://github.com/FreeOpcUa/python-opcua/pull/274

**Comment by oroulet** [comment]
The issue with args and kwargs is that they hide what arguments the method are expecting to users. so I think I will merge bitkeeper solution.

**Comment by bitkeeper** [comment]
Are we not making the problem bigger than it is ?
Just restoring the items is already cleaner then the current situation. Easy to read/maintain, IDE friendly. And it is the situation then we already had for sometime.

Maybe create a new issue to reduce the fat interface of node (take also the other functions of node in account). I believe that subclassing (like indicated by @georgschoelly ) is in the end the way to go compared to extend and simple assigments.

**Pull request merged**
