### PR TITLE
Don't wait on close_session() when underlying socket is closed

### PR DESCRIPTION
**Pull request by brubbel**
cfr. https://github.com/FreeOpcUa/python-opcua/issues/905

### CODE REVIEW

**Comment by brubbel** [comment]
Update https://github.com/FreeOpcUa/python-opcua/pull/906/commits/e269e429638802c82597a7e90f03367e245cc5e8:
Don't wait for future timeout when underlying socket is closed.

**Comment by oroulet** [comment]
Finished? No idea if this is correct but your explanation makes sense

**Comment by brubbel** [comment]
Not yet, there will be some additional changes later on.

**Comment by oroulet** [comment]
Change name to start with wip: then. So everybody knows it is work in progress

**Comment by brubbel** [comment]
Ready

**Pull request merged**
