### PR TITLE
Support server-side secure connections

### PR DESCRIPTION
**Pull request by alkor**
Moved most of the common logic to uaprotocol.SecureConnection class.
Example of server with security enabled:
```
tools/uaserver --populate --certificate cert.pem --private_key pk.pem
```

### CODE REVIEW

**Comment by oroulet** [comment]
tests failed with pypy for your pull request... tests hang with pypy in my last commit. Seems to be a race condition somewhere that pypy exposes..... Maybe you can find out looking at your error?

**Comment by alkor** [comment]
Yes, I'm trying to find what's wrong. Tests run successfully on my machine.

**Comment by oroulet** [comment]
not sure it is your fault... might be a bug that your changes expose...

**Comment by alkor** [comment]
Hmm, I tried to setup.py install and saw that only a few files were installed. Now I see that there is another error.

**Comment by oroulet** [comment]
if you merge the changes from #101 does it help?

**Comment by oroulet** [comment]
I did not want to send the restructuring to master. That was a mistake
sorry...

**Comment by alkor** [comment]
Yes, looks like #101 helps. Travis reports success.

**Comment by oroulet** [comment]
merged manually

**Comment by oroulet** [comment]
> tools/uaserver --populate --certificate cert.pem --private_key pk.pem

Could you write a minimal_server_with_encryption.py ? so we have it documented? I will update the README

**Comment by oroulet** [comment]
I have not tested yet, but it looks like you did a very good job! ... as usual..

**Pull request closed without merging**
