### PR TITLE
Register nodes

### PR DESCRIPTION
**Pull request by sdransfeld**
Add some functions to increase read/write speed. Tested with Siemens PLC.

### CODE REVIEW

**Comment by oroulet** [comment]
The low level stuff is completely done, but I am not very keen in changing self.nodeid of a Node. That may surprise users and lead to all kinds of strange behaviours. What about simply returning a list of new nodes? Maybe even creating a Node superset that has a old_nodeid attribute of you want

**Comment by sdransfeld** [comment]
But, when using node.register(), should this return a new node? Then the
user must track two nodes. In my opinion this is not very elegant and
intuitive either.

Another possibility is that the registered node is hidden for the user, and
only used in communication with the server. The problem with this solution
is that it probably requires a lot of small changes.

Den tir. 2. apr. 2019, 18:18 skrev oroulet <notifications@github.com>:

**Comment by oroulet** [comment]
I agree that returning a new node is strange,. but this is what the opcua protocol specifies, so I am afraid to hide it away. 
you can always change the node id locally in you application if you want, in order to not have to handle two nodes
btw I am quite sure that in most applications, you will register your node then overwrite you local node variable with the new registered node. There is probably no reason to keep track of original node after registration

**Comment by sdransfeld** [comment]
If you unregister the node, you would want the old nodeid back. So to have
this functionality we need to store the original nodeid.

The patch is currently wrong, need some fixups.

**Comment by oroulet** [comment]
merged

**Pull request closed without merging**
