### PR TITLE
Unsub list handle

### PR DESCRIPTION
**Pull request by swamper123**
Fix double listing like mentioned in #1096

### CODE REVIEW

**Comment by oroulet** [comment]
seems to break something

**Comment by swamper123** [comment]
Jep ... I will investigate it today. I guess the handling with single lists was not expected.

**Comment by lkaupp** [comment]
Found your error:
```
        handles = [handle] if type(handle) is int else handle # you spare this operation
        if not handles:
            return
        params = ua.DeleteMonitoredItemsParameters()
        params.SubscriptionId = self.subscription_id
        params.MonitoredItemIds = handle #should be "handles" not handle
```

**Comment by swamper123** [comment]
@lkaupp A wise man told me once: "If you hear hooves stamping, you should think about horses not zebras." 
Well I was looking for zebras everywhere, but not the horse I placed myself there. Thanks for the hint.
It seems that there are some other issues as well. Travis may accept the tests, but Errors still appear. But this is something for other issues.

**Pull request merged**
