### PR TITLE
Xml server example

### PR DESCRIPTION
**Pull request by levkevi**

### CODE REVIEW

**Comment by zerox1212** [comment]
Can you give some more description about the purpose of this example?

**Comment by levkevi** [comment]
There was no simple examples that mapped a method that was imported from a Xml file to a function. There is also no function that returns a list of value. The example show how to do a server that does that and what the server gets back when using the methods. 

I also handle the connection using a context manager so it always closes if there is an exception.

**Comment by oroulet** [comment]
nice code

**Comment by zerox1212** [comment]
FYI you can also put your method into the XML, then you can link the python function with `server.link_method`.

**Comment by oroulet** [comment]
@zerox1212 good point. we should update the example

**Pull request merged**
