### PR TITLE
Fixed minor issue #424 EngeineeringUnits could not be parsed

### PR DESCRIPTION
**Pull request by XB32Z**
The value was not str but unicode
Pierre

### CODE REVIEW

**Comment by zerox1212** [comment]
I will let @oroulet comment, but I think this should maybe be fixed in `xmlparser`.

**Comment by oroulet** [comment]
But thanks for the fix, if you can make it work with python 3 without to much code, I will merge

**Comment by zerox1212** [comment]
I think a better solution would probably be to add `.encode('utf-8)` some where or maybe the XML parser should enforce an encoding.

**Comment by XB32Z** [comment]
Hi all, 

Sorry I didn't checked on PYthon3. I found a [solution ](http://stackoverflow.com/questions/4843173/how-to-check-if-type-of-a-variable-is-string) which includes importing another compatibility library (six) and replacing str by six.string_type. Does this fit you? Encoding the file in utf8 did not solved the issue. 

Best

**Comment by oroulet** [comment]
om several files we have: 

if sys.version_info.major > 2:
    unicode = str


lets do the same here.
So you can write isintance(xxx, (str, unicode)) instead of or

**Comment by zerox1212** [comment]
I would still like to know the root cause of why the parser would pass a unicode object instead of a string object to the importer.

**Comment by oroulet** [comment]
You are right there might be something strange here.

**Comment by XB32Z** [comment]
This field (<uax:Text>) can have values such as "m²" maybe the parser always reads it as unicode because it can have special characters?

**Comment by zerox1212** [comment]
After some reading this should be fixed in the parser. Python 2.7 and Python 3+ have different versions of Etree which handle encoding differently.

@XB32Z can you attached your XML file? The encoding of an XML should always be declared at the top. This declaration is used by the parser internally.

**Comment by XB32Z** [comment]
Cf quote in #424 
A simple node from AnalogDataType with EUEngineeringUnit properties will give the error

**Comment by zerox1212** [comment]
Do you have this at the top of the file you are importing?
`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by XB32Z** [comment]
No I did not, however I added it and I still have the error

**Comment by zerox1212** [comment]
If I get time I will look at how to make the Etree encoding work correctly for 2.7 and 3. For now your fix will work.

**Pull request merged**
