### PR TITLE
changed Nodeclass  __str__ and __repr__ method

### PR DESCRIPTION
**Pull request by AndreasHeine**
#1057:

    def __str__(self):
        return self.nodeid[self.nodeid.find("(")+1:self.nodeid.find(")")]
    
    def __repr__(self):
        return "Node({0})".format(self.nodeid)

"str(node)" => "ns=2;i=2" and if you call repr(node) => Node(NumericNodeId(ns=2;i=2))

### CODE REVIEW

**Comment by AndreasHeine** [comment]
... made a mistak (-_-) one sec

**Comment by AndreasHeine** [comment]
```
    def __str__(self):
        node_str = str(self.nodeid)
        return node_str[node_str.find("(")+1:node_str.find(")")]

    def __repr__(self):
        return "Node({0})".format(self.nodeid)
```

**Comment by swamper123** [comment]
Just a question, because I'm not so into oder NodeID types: Is it possible that `\"` or `"` could be part of the nodeid? May this cause trouble?

**Comment by AndreasHeine** [comment]
could you provide an example, i am not sure what you mean?

**Comment by swamper123** [comment]
Something like this:
`"ns=2;s=iams\"anode"` or `"ns=2;b=k2309"lq='"`

**Comment by AndreasHeine** [comment]
i guess this will break something!

**Comment by swamper123** [comment]
Maybe it would be better to construct a clean nodeid string from it's base:

`return f"ns={NamespaceIndex},{NodeIdType}={Identifier}"`
For the NodeIdType the used letter shall be added.

**Comment by AndreasHeine** [comment]
plan was to get something like: 
"ns=2;i=2" or "ns=2;s=MyTemperature" or ns=1;g=09087e75-8e5e-499b-954f-f2a9603db28a 
from -> str(node)

instead on this "Node(NumericNodeId(ns=2;i=2))"

guess you mean the same!

**Comment by AndreasHeine** [comment]
> Something like this:
> "ns=2;s=iams\"anode" or "ns=2;b=k2309"lq='"

maybe its possible to escape some charakters but its a more general problem/question witch chars are allowed in a OPC UA

**Comment by swamper123** [comment]
Yes I mean the same. I also have no clue how other Server/Client provider deal with such things. 
I would guess many other languages have their "special chars" which they have to deal with as well (or it hasn't happened yet).

**Comment by AndreasHeine** [comment]
@swamper123 : ive tested some different node ids

> Something like this:
> "ns=2;s=iams\"anode" or "ns=2;b=k2309"lq='"

you brought me to think more about it...

```
    var1 = await obj.add_variable(ua.NodeId.from_string(f'ns={idx};s=s=iams\"//a/node'), 'var1', 0)
result => ns=2;s=s=iams"//a/node
    var2 = await obj.add_variable(ua.NodeId.from_string(f'ns={idx};s=b=k2309;"lq='), 'var2', 0)
result => ns=2;s=b=k2309
```

you can use most speacial charakters! but not ";" "{" "}" => 'ns=2;s=b=k2309;"lq=' => "ns=2;s=b=k2309"
and you have to make sure that that you dont break the string like: "asdf"1234" instead 'asdf"1234'
or in my opinion the safest way to do it """ns=2;s=b=k"23'0\9;"lq=""" so you use " and ' and / and \

**Pull request merged**
