### PR TITLE
v1.04

### PR DESCRIPTION
**Pull request by ipa-hsd**
Finally able to generate the address spaces. The solution maybe a hack (but in the current version as well, `ArrayDimensions` was not written to the output file).

Couple of warnings / errors I got:
```shell
$ python3 generate_protocol_python.py

Parsing:  Opc.Ua.Types.bsd
Unknown attr for enum:  IsOptionSet

Writting python protocol code to  ../opcua/ua/uaprotocol_auto.py
```
and
```
$ python3 generate_event_objects.py 

Parsing: Opc.Ua.NodeSet2.xml
Traceback (most recent call last):
  File "generate_event_objects.py", line 118, in <module>
    ECG.generateEventsCode(model)
  File "generate_event_objects.py", line 102, in generateEventsCode
    self.generateEventclass(event, parentNode.browseName)
  File "generate_event_objects.py", line 90, in generateEventclass
    self.addProperties(event)
  File "generate_event_objects.py", line 37, in addProperties
    self.write("self.add_property('{0}', {1}, {2})".format(ref.refBrowseName, self.getPropertyValue(ref), self.getPropertyDataType(ref)))
  File "generate_event_objects.py", line 49, in getPropertyValue
    return "ua.NodeId(ua.ObjectIds.{0})".format(str(obIds.ObjectIdNames[int(str(reference.refId).split("=")[1])]).split("_")[0])
KeyError: 15545
```
and finally the address spaces are generated:
```
$ python3 generate_address_space.py 

Generating Python code ../opcua/server/standard_address_space/standard_address_space_part3.py for XML file Opc.Ua.NodeSet2.Part3.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part4.py for XML file Opc.Ua.NodeSet2.Part4.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part5.py for XML file Opc.Ua.NodeSet2.Part5.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part8.py for XML file Opc.Ua.NodeSet2.Part8.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part9.py for XML file Opc.Ua.NodeSet2.Part9.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part10.py for XML file Opc.Ua.NodeSet2.Part10.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part11.py for XML file Opc.Ua.NodeSet2.Part11.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part13.py for XML file Opc.Ua.NodeSet2.Part13.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part14.py for XML file Opc.Ua.NodeSet2.Part14.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part17.py for XML file Opc.Ua.NodeSet2.Part17.xml
Generating Python code ../opcua/server/standard_address_space/standard_address_space_part19.py for XML file Opc.Ua.NodeSet2.Part19.xml
Savind standard address space to: ../opcua/binary_address_space.pickle
```

### CODE REVIEW

**Comment by ipa-hsd** [comment]
But the tests are failing, don't know why :/
Do you think the tests need to be updated as well?

**Comment by oroulet** [comment]
so your solution is to not write the ArrayDimensions parameter at all??
Also where did you find the split xml nodeset files? they are not on opc foundation anymore... https://opcfoundation.org/UA/schemas/1.04/

**Comment by oroulet** [comment]
so your solution is to not write the ArrayDimensions parameter at all??
Also where did you find the split xml nodeset files? they are not on opc foundation anymore... https://opcfoundation.org/UA/schemas/1.04/
Also nowit looks like you got another issue. Someone broke the LocalizedText generation...

**Comment by ipa-hsd** [comment]
I got it from [here](https://github.com/OPCFoundation/UA-Nodeset/tree/master/Schema)

**Comment by oroulet** [comment]
Great. Nice to know they still exist!

**Comment by ipa-hsd** [comment]
Isn't `ArrayDimensions` already being written here?
https://github.com/FreeOpcUa/python-opcua/blob/4119e74be91091e7ae0f72dcfed24c5334d691df/schemas/generate_address_space.py#L217

I am not sure what's to be done with the one 2nd one...

**Comment by ipa-hsd** [comment]
Alright, I am writing the following to the output file now:
```py
self.writecode(indent, 'extobj.ArrayDimensions = {0}'.format(v[0][1]))
```
Is it OK to just ignore the `<UInt32>`?  

also adding the imports to all the `standard_address_space_part{x}.py` files:
```py
import datetime
from dateutil.tz import tzutc
```
I still have not figured out the issue with the `LocalizedText` generation. Any hints?

**Comment by oroulet** [comment]
fixed a few fix and merged. thanks for the help

**Comment by ipa-hsd** [comment]
I am not sure if disabling the tests is a "fix". I will try to debug it this week and reopen the PR.

**Comment by oroulet** [comment]
Help welcome. It is at least in much better shape now

**Comment by oroulet** [comment]
Also just to make sure we understand each others: I disabled one test for something I did not understand, but everything else (there were several small things) is fixed

**Comment by ipa-hsd** [comment]
Alright, thanks.  
I saw commit messages like "although maybe wrong" and "ugly hack". If you want I can take a look into it sometime this week.

**Pull request closed without merging**
