### PR TITLE
Improved handling of references

### PR DESCRIPTION
**Pull request by ipa-mdl**
add test for generated address space (#508)
Prints all skipped references(currently 1370) and nodes (0).

### CODE REVIEW

**Comment by ipa-mdl** [comment]
I have added the patches for the generator, but I cannot run it.
Even for the master I get
```
Traceback (most recent call last):
  File "generate_address_space.py", line 289, in <module>
    c.run()
  File "generate_address_space.py", line 51, in run
    self.make_variable_code(node)
  File "generate_address_space.py", line 186, in make_variable_code
    self.make_common_variable_code(indent, obj)
  File "generate_address_space.py", line 141, in make_common_variable_code
    self.make_ext_obj_code(indent, ext)
  File "generate_address_space.py", line 169, in make_ext_obj_code
    val = _to_val([extobj.objname], k, v)
  File "generate_address_space.py", line 19, in _to_val
    return ua_type_to_python(val, cls.ua_types[attr])
TypeError: list indices must be integers or slices, not str
```

**Comment by oroulet** [comment]
Sorry. there was a missing update after a huge change a few weeks ago. Fixed now in master

**Comment by oroulet** [comment]
your PR looks good. rebase and test and we can merge it

**Comment by ipa-mdl** [comment]
Still 93 references left..

**Comment by ipa-mdl** [comment]
@oroulet: part 3 and 5 depend on each other, any idea how to solve this?

**Comment by ipa-mdl** [comment]
some parents get references before they got defined.

**Comment by oroulet** [comment]
Looks like you already have the solution with your design. store refs in your class and call add_references after all imports..... Isn't it?

**Comment by ipa-mdl** [comment]
> Looks like you already have the solution with your design. store refs in your class and call add_references after all imports..... Isn't it?

Yes, there seems to be no alternative to storing the failing refs.
I don't know why the other tests fail, even for the [master](https://travis-ci.org/FreeOpcUa/python-opcua/builds/298224143).

**Comment by ipa-mdl** [comment]
@oroulet: ready for review :)

**Comment by ipa-mdl** [comment]
bind problems: https://github.com/travis-ci/travis-ci/issues/8711

**Comment by ipa-mdl** [comment]
For some reason sub types which are imported from XML might have duplicated properties (identtical nodeid),

**Comment by ipa-mdl** [comment]
Summary:
- implemented fix for #508, plus in XML importer
- enforcing uniqueness of references
- add Node interfaces for adding and deleting references 
- minor improvements

**Comment by oroulet** [comment]
Do the tests pass now?

**Comment by ipa-mdl** [comment]
> Do the tests pass now?

Yes, but only with the IPv4 hack
This PR changes the overall behaviour as new references gets added  etc.

**Comment by oroulet** [comment]
Looks good. My only comment is that I do not like asserts. Especially on things that are not critical like missing reference in addresses space
 Better to write a warning

**Comment by ipa-mdl** [comment]
Thanks for merging!

> My only comment is that I do not like asserts.

I hopefully have used them for invariants only :)

**Pull request merged**
